# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2
    
notifications:
  email:
    recipients:
      - cappertone@gmail.com
    on_success: always # default: change
    on_failure: always # default: always