language: java
jdk: oraclejdk8
dist: trusty
before_install:
  - mysql -e 'CREATE DATABASE studypet;'
install: true
services:
  - mysql

test:
  adapter: mysql2
  database: studypet
  username: travis
  encoding: utf8